package com.org.source.test;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ARTICLE_IMAGE.
 */
public class ArticleImage {

    private Long id;
    private String title;
    private Short index;
    private String description;
    private Short width;
    private Short height;
    private String type;
    private String url;
    private String gallery_id;
    private Short gallery_type;
    /** Not-null value. */
    private String aid;

    public ArticleImage() {
    }

    public ArticleImage(Long id) {
        this.id = id;
    }

    public ArticleImage(Long id, String title, Short index, String description, Short width, Short height, String type, String url, String gallery_id, Short gallery_type, String aid) {
        this.id = id;
        this.title = title;
        this.index = index;
        this.description = description;
        this.width = width;
        this.height = height;
        this.type = type;
        this.url = url;
        this.gallery_id = gallery_id;
        this.gallery_type = gallery_type;
        this.aid = aid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Short getIndex() {
        return index;
    }

    public void setIndex(Short index) {
        this.index = index;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Short getWidth() {
        return width;
    }

    public void setWidth(Short width) {
        this.width = width;
    }

    public Short getHeight() {
        return height;
    }

    public void setHeight(Short height) {
        this.height = height;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getGallery_id() {
        return gallery_id;
    }

    public void setGallery_id(String gallery_id) {
        this.gallery_id = gallery_id;
    }

    public Short getGallery_type() {
        return gallery_type;
    }

    public void setGallery_type(Short gallery_type) {
        this.gallery_type = gallery_type;
    }

    /** Not-null value. */
    public String getAid() {
        return aid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAid(String aid) {
        this.aid = aid;
    }

}
