package com.org.source.test;

import java.util.List;
import com.org.source.greendao.dao.DaoSession;
import com.org.source.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ARTICLE.
 */
public class Article {

    private Long id;
    private String attribute;
    private Short comment_cnt;
    private String content;
    private Short content_type;
    private String grab_time;
    private long cid;
    private Short item_type;
    private String matched_tag;
    private Short oppose_cnt;
    private String original_url;
    private String publish_time;
    private Short reco_type;
    private Long recoid;
    private String site;
    private String source_name;
    private String summary;
    private Short support_cnt;
    private String title;
    private String url;
    private Boolean valid;


    private List<ArticleImage> image;
    private List<ArticleThumbnail> thumbnails;

    private List<String> special_content;
    private List<String> tags;

    public Article() {
    }

    public Article(Long id) {
        this.id = id;
    }

    public Article(Long id, String attribute, Short comment_cnt, String content, Short content_type, String grab_time, long cid, Short item_type, String matched_tag, Short oppose_cnt, String original_url, String publish_time, Short reco_type, Long recoid, String site, String source_name, String summary, Short support_cnt, List<String> tags, String title, String url, Boolean valid) {
        this.id = id;
        this.attribute = attribute;
        this.comment_cnt = comment_cnt;
        this.content = content;
        this.content_type = content_type;
        this.grab_time = grab_time;
        this.cid = cid;
        this.item_type = item_type;
        this.matched_tag = matched_tag;
        this.oppose_cnt = oppose_cnt;
        this.original_url = original_url;
        this.publish_time = publish_time;
        this.reco_type = reco_type;
        this.recoid = recoid;
        this.site = site;
        this.source_name = source_name;
        this.summary = summary;
        this.support_cnt = support_cnt;
        this.tags = tags;
        this.title = title;
        this.url = url;
        this.valid = valid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public List<String> getSpecial_content() {
        return special_content;
    };
    
    public void setSpecial_content(List<String> special_content) {
        this.special_content = special_content;
    }
    
    public String getAttribute() {
        return attribute;
    }

    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    public Short getComment_cnt() {
        return comment_cnt;
    }

    public void setComment_cnt(Short comment_cnt) {
        this.comment_cnt = comment_cnt;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Short getContent_type() {
        return content_type;
    }

    public void setContent_type(Short content_type) {
        this.content_type = content_type;
    }

    public String getGrab_time() {
        return grab_time;
    }

    public void setGrab_time(String grab_time) {
        this.grab_time = grab_time;
    }

    public long getCid() {
        return cid;
    }

    public void setCid(long cid) {
        this.cid = cid;
    }

    public Short getItem_type() {
        return item_type;
    }

    public void setItem_type(Short item_type) {
        this.item_type = item_type;
    }

    public String getMatched_tag() {
        return matched_tag;
    }

    public void setMatched_tag(String matched_tag) {
        this.matched_tag = matched_tag;
    }

    public Short getOppose_cnt() {
        return oppose_cnt;
    }

    public void setOppose_cnt(Short oppose_cnt) {
        this.oppose_cnt = oppose_cnt;
    }

    public String getOriginal_url() {
        return original_url;
    }

    public void setOriginal_url(String original_url) {
        this.original_url = original_url;
    }

    public String getPublish_time() {
        return publish_time;
    }

    public void setPublish_time(String publish_time) {
        this.publish_time = publish_time;
    }

    public Short getReco_type() {
        return reco_type;
    }

    public void setReco_type(Short reco_type) {
        this.reco_type = reco_type;
    }

    public Long getRecoid() {
        return recoid;
    }

    public void setRecoid(Long recoid) {
        this.recoid = recoid;
    }

    public String getSite() {
        return site;
    }

    public void setSite(String site) {
        this.site = site;
    }

    public String getSource_name() {
        return source_name;
    }

    public void setSource_name(String source_name) {
        this.source_name = source_name;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public Short getSupport_cnt() {
        return support_cnt;
    }

    public void setSupport_cnt(Short support_cnt) {
        this.support_cnt = support_cnt;
    }
    
    public List<String> getTags() {
        return tags;
    }
    
    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Boolean getValid() {
        return valid;
    }

    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    public List<ArticleImage> getImage() {
        return image;
    }

    public List<ArticleThumbnail> getThumbnails() {
        return thumbnails;
    }


}
