package com.org.source.test;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import com.org.source.greendao.AbstractDao;
import com.org.source.greendao.AbstractDaoSession;
import com.org.source.greendao.identityscope.IdentityScopeType;
import com.org.source.greendao.internal.DaoConfig;

import com.org.source.test.Channel;
import com.org.source.test.Article;
import com.org.source.test.ArticleImage;
import com.org.source.test.ArticleThumbnail;

import com.org.source.test.ChannelDao;
import com.org.source.test.ArticleDao;
import com.org.source.test.ArticleImageDao;
import com.org.source.test.ArticleThumbnailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig channelDaoConfig;
    private final DaoConfig articleDaoConfig;
    private final DaoConfig articleImageDaoConfig;
    private final DaoConfig articleThumbnailDaoConfig;

    private final ChannelDao channelDao;
    private final ArticleDao articleDao;
    private final ArticleImageDao articleImageDao;
    private final ArticleThumbnailDao articleThumbnailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        channelDaoConfig = daoConfigMap.get(ChannelDao.class).clone();
        channelDaoConfig.initIdentityScope(type);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        articleImageDaoConfig = daoConfigMap.get(ArticleImageDao.class).clone();
        articleImageDaoConfig.initIdentityScope(type);

        articleThumbnailDaoConfig = daoConfigMap.get(ArticleThumbnailDao.class).clone();
        articleThumbnailDaoConfig.initIdentityScope(type);

        channelDao = new ChannelDao(channelDaoConfig, this);
        articleDao = new ArticleDao(articleDaoConfig, this);
        articleImageDao = new ArticleImageDao(articleImageDaoConfig, this);
        articleThumbnailDao = new ArticleThumbnailDao(articleThumbnailDaoConfig, this);

        registerDao(Channel.class, channelDao);
        registerDao(Article.class, articleDao);
        registerDao(ArticleImage.class, articleImageDao);
        registerDao(ArticleThumbnail.class, articleThumbnailDao);
    }
    
    public void clear() {
        channelDaoConfig.getIdentityScope().clear();
        articleDaoConfig.getIdentityScope().clear();
        articleImageDaoConfig.getIdentityScope().clear();
        articleThumbnailDaoConfig.getIdentityScope().clear();
    }

    public ChannelDao getChannelDao() {
        return channelDao;
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public ArticleImageDao getArticleImageDao() {
        return articleImageDao;
    }

    public ArticleThumbnailDao getArticleThumbnailDao() {
        return articleThumbnailDao;
    }

}
