package com.org.source.test;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import com.org.source.greendao.AbstractDao;
import com.org.source.greendao.AbstractDaoSession;
import com.org.source.greendao.identityscope.IdentityScopeType;
import com.org.source.greendao.internal.DaoConfig;

import com.org.source.test.Channel;

import com.org.source.test.ChannelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig channelDaoConfig;

    private final ChannelDao channelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        channelDaoConfig = daoConfigMap.get(ChannelDao.class).clone();
        channelDaoConfig.initIdentityScope(type);

        channelDao = new ChannelDao(channelDaoConfig, this);

        registerDao(Channel.class, channelDao);
    }
    
    public void clear() {
        channelDaoConfig.getIdentityScope().clear();
    }

    public ChannelDao getChannelDao() {
        return channelDao;
    }

}
