package com.org.source.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ARTICLE_THUMBNAIL.
 */
public class ArticleThumbnail {

    private Long id;
    private Short width;
    private Short height;
    private String url;
    private long aid;

    public ArticleThumbnail() {
    }

    public ArticleThumbnail(Long id) {
        this.id = id;
    }

    public ArticleThumbnail(Long id, Short width, Short height, String url, long aid) {
        this.id = id;
        this.width = width;
        this.height = height;
        this.url = url;
        this.aid = aid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Short getWidth() {
        return width;
    }

    public void setWidth(Short width) {
        this.width = width;
    }

    public Short getHeight() {
        return height;
    }

    public void setHeight(Short height) {
        this.height = height;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public long getAid() {
        return aid;
    }

    public void setAid(long aid) {
        this.aid = aid;
    }

}
