package com.org.source.sm.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.org.source.greendao.AbstractDao;
import com.org.source.greendao.Property;
import com.org.source.greendao.internal.SqlUtils;
import com.org.source.greendao.internal.DaoConfig;
import com.org.source.greendao.query.Query;
import com.org.source.greendao.query.QueryBuilder;

import com.org.source.sm.model.ArticleToTag;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ARTICLE_TO_TAG.
*/
public class ArticleToTagDao extends AbstractDao<ArticleToTag, Long> {

    public static final String TABLENAME = "ARTICLE_TO_TAG";

    /**
     * Properties of entity ArticleToTag.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Aid = new Property(1, String.class, "aid", false, "AID");
        public final static Property Tid = new Property(2, String.class, "tid", false, "TID");
    };

    private DaoSession daoSession;

    private Query<ArticleToTag> article_ArticleToTagQuery;
    private Query<ArticleToTag> tag_ArticleToTagQuery;

    public ArticleToTagDao(DaoConfig config) {
        super(config);
    }
    
    public ArticleToTagDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ARTICLE_TO_TAG' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'AID' TEXT NOT NULL ," + // 1: aid
                "'TID' TEXT NOT NULL );"); // 2: tid
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ARTICLE_TO_TAG'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ArticleToTag entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getAid());
        stmt.bindString(3, entity.getTid());
    }

    @Override
    protected void attachEntity(ArticleToTag entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ArticleToTag readEntity(Cursor cursor, int offset) {
        ArticleToTag entity = new ArticleToTag( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // aid
            cursor.getString(offset + 2) // tid
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ArticleToTag entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAid(cursor.getString(offset + 1));
        entity.setTid(cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ArticleToTag entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ArticleToTag entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "articleToTag" to-many relationship of Article. */
    public List<ArticleToTag> _queryArticle_ArticleToTag(String aid) {
        synchronized (this) {
            if (article_ArticleToTagQuery == null) {
                QueryBuilder<ArticleToTag> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Aid.eq(null));
                article_ArticleToTagQuery = queryBuilder.build();
            }
        }
        Query<ArticleToTag> query = article_ArticleToTagQuery.forCurrentThread();
        query.setParameter(0, aid);
        return query.list();
    }

    /** Internal query to resolve the "articleToTag" to-many relationship of Tag. */
    public List<ArticleToTag> _queryTag_ArticleToTag(String tid) {
        synchronized (this) {
            if (tag_ArticleToTagQuery == null) {
                QueryBuilder<ArticleToTag> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Tid.eq(null));
                tag_ArticleToTagQuery = queryBuilder.build();
            }
        }
        Query<ArticleToTag> query = tag_ArticleToTagQuery.forCurrentThread();
        query.setParameter(0, tid);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTagDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getArticleDao().getAllColumns());
            builder.append(" FROM ARTICLE_TO_TAG T");
            builder.append(" LEFT JOIN TAG T0 ON T.'TID'=T0.'TAG'");
            builder.append(" LEFT JOIN ARTICLE T1 ON T.'AID'=T1.'ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ArticleToTag loadCurrentDeep(Cursor cursor, boolean lock) {
        ArticleToTag entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Tag tag = loadCurrentOther(daoSession.getTagDao(), cursor, offset);
         if(tag != null) {
            entity.setTag(tag);
        }
        offset += daoSession.getTagDao().getAllColumns().length;

        Article article = loadCurrentOther(daoSession.getArticleDao(), cursor, offset);
         if(article != null) {
            entity.setArticle(article);
        }

        return entity;    
    }

    public ArticleToTag loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ArticleToTag> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ArticleToTag> list = new ArrayList<ArticleToTag>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ArticleToTag> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ArticleToTag> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
