package com.org.source.sm.model;


import java.util.List;
// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CHANNEL.
 */
public class Channel {

    private Long id;
    /** Not-null value. */
    private String name;
    private Short status;
    private Boolean is_fixed;
    private Boolean is_subscribed;
    private Short show_type;

    private List<Article> articles;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Channel() {
    }

    public Channel(Long id) {
        this.id = id;
    }

    public Channel(Long id, String name, Short status, Boolean is_fixed, Boolean is_subscribed, Short show_type) {
        this.id = id;
        this.name = name;
        this.status = status;
        this.is_fixed = is_fixed;
        this.is_subscribed = is_subscribed;
        this.show_type = show_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Short getStatus() {
        return status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    public Boolean getIs_fixed() {
        return is_fixed;
    }

    public void setIs_fixed(Boolean is_fixed) {
        this.is_fixed = is_fixed;
    }

    public Boolean getIs_subscribed() {
        return is_subscribed;
    }

    public void setIs_subscribed(Boolean is_subscribed) {
        this.is_subscribed = is_subscribed;
    }

    public Short getShow_type() {
        return show_type;
    }

    public void setShow_type(Short show_type) {
        this.show_type = show_type;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Article> getArticles() {
        if (articles == null) {
            ArticleDao targetDao = DaoHelper.getDaoSession().getArticleDao();
            List<Article> articlesNew = targetDao._queryChannel_Articles(id);
            synchronized (this) {
                if(articles == null) {
                    articles = articlesNew;
                }
            }
        }
        return articles;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetArticles() {
        articles = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        DaoHelper.getDaoSession().getChannelDao().delete(this);  
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        DaoHelper.getDaoSession().getChannelDao().update(this);  
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        DaoHelper.getDaoSession().getChannelDao().refresh(this);  
    }

    // KEEP METHODS - put your custom methods here
    public void save() {
        DaoHelper.getDaoSession().getChannelDao().insertOrReplace(this);
    }
    // KEEP METHODS END

}
