package com.org.source.sm.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import com.org.source.greendao.AbstractDao;
import com.org.source.greendao.AbstractDaoSession;
import com.org.source.greendao.identityscope.IdentityScopeType;
import com.org.source.greendao.internal.DaoConfig;


import com.org.source.sm.model.Article;
import com.org.source.sm.model.ArticleDao;
import com.org.source.sm.model.ArticleImage;
import com.org.source.sm.model.ArticleImageDao;
import com.org.source.sm.model.ArticleThumbnail;
import com.org.source.sm.model.ArticleThumbnailDao;
import com.org.source.sm.model.ArticleToTag;
import com.org.source.sm.model.ArticleToTagDao;
import com.org.source.sm.model.Channel;
import com.org.source.sm.model.ChannelDao;
import com.org.source.sm.model.Tag;
import com.org.source.sm.model.TagDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig channelDaoConfig;
    private final DaoConfig tagDaoConfig;
    private final DaoConfig articleToTagDaoConfig;
    private final DaoConfig articleDaoConfig;
    private final DaoConfig articleImageDaoConfig;
    private final DaoConfig articleThumbnailDaoConfig;

    private final ChannelDao channelDao;
    private final TagDao tagDao;
    private final ArticleToTagDao articleToTagDao;
    private final ArticleDao articleDao;
    private final ArticleImageDao articleImageDao;
    private final ArticleThumbnailDao articleThumbnailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        channelDaoConfig = daoConfigMap.get(ChannelDao.class).clone();
        channelDaoConfig.initIdentityScope(type);

        tagDaoConfig = daoConfigMap.get(TagDao.class).clone();
        tagDaoConfig.initIdentityScope(type);

        articleToTagDaoConfig = daoConfigMap.get(ArticleToTagDao.class).clone();
        articleToTagDaoConfig.initIdentityScope(type);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        articleImageDaoConfig = daoConfigMap.get(ArticleImageDao.class).clone();
        articleImageDaoConfig.initIdentityScope(type);

        articleThumbnailDaoConfig = daoConfigMap.get(ArticleThumbnailDao.class).clone();
        articleThumbnailDaoConfig.initIdentityScope(type);

        channelDao = new ChannelDao(channelDaoConfig, this);
        tagDao = new TagDao(tagDaoConfig, this);
        articleToTagDao = new ArticleToTagDao(articleToTagDaoConfig, this);
        articleDao = new ArticleDao(articleDaoConfig, this);
        articleImageDao = new ArticleImageDao(articleImageDaoConfig, this);
        articleThumbnailDao = new ArticleThumbnailDao(articleThumbnailDaoConfig, this);

        registerDao(Channel.class, channelDao);
        registerDao(Tag.class, tagDao);
        registerDao(ArticleToTag.class, articleToTagDao);
        registerDao(Article.class, articleDao);
        registerDao(ArticleImage.class, articleImageDao);
        registerDao(ArticleThumbnail.class, articleThumbnailDao);
    }
    
    public void clear() {
        channelDaoConfig.getIdentityScope().clear();
        tagDaoConfig.getIdentityScope().clear();
        articleToTagDaoConfig.getIdentityScope().clear();
        articleDaoConfig.getIdentityScope().clear();
        articleImageDaoConfig.getIdentityScope().clear();
        articleThumbnailDaoConfig.getIdentityScope().clear();
    }

    public ChannelDao getChannelDao() {
        return channelDao;
    }

    public TagDao getTagDao() {
        return tagDao;
    }

    public ArticleToTagDao getArticleToTagDao() {
        return articleToTagDao;
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public ArticleImageDao getArticleImageDao() {
        return articleImageDao;
    }

    public ArticleThumbnailDao getArticleThumbnailDao() {
        return articleThumbnailDao;
    }

}
